### ISSUE TITLE
Too much code duplicated from JOSM core

### ISSUE THREAD

**Issue by don-vip** [GeoKnow/OSMRec#2]
Hi,
JOSM developer here.
I like the idea of this plugin, but the way it has been created is a bit problematic for us since it it now hosted on OSM SVN.

The two classes OSMRecToggleDialog and OSMRecPluginHelper are basically copies of two major JOSM classes (PropertiesDialog and TagEditHelper) that reference a lot of internal code of JOSM that should not be called in this plugin, since 90% of the code itself is not used.

Could you please strip these classes to the bare minimum, by keeping only features you want to use? The problem with this approach is that, each time we need to update method signatures or public API that has been copied to the plugin, we need to update it without a good reason because we're technically speaking about dead code.

Thanks.

**Comment by nkaragiannakis** [comment]
Hi,
you are right, i will clean the dead code soon.

**Comment by nkaragiannakis** [comment]
I cleaned up most of the code (OSMRecToggleDialog basically) and commit the new version.
Let me know if there is anything else or another approach to minimize the affects of future core changes to the plugin.
Thank you!

**Comment by don-vip** [comment]
@simon04 initiated a patch to improve further the situation, can you please give it a look? It's here: https://josm.openstreetmap.de/ticket/12281
