### ISSUE TITLE
Use plugin dependencies instead of duplicating COTS

### ISSUE THREAD

**Issue by don-vip** [GeoKnow/OSMRec#3]
Hi again,

There is another problem with the current implementation: a lot of standard COTS are directly integrated in the plugin. It causes problem when other JOSM plugins are installed, which contains conflicting versions of the same COTS.

For example GeoTools is used by several plugins => The solution has been to create a dedicated plugin (geotools) which provides the library. Thus, other JOSM plugins need only to specify in their manifest that they need it. It also greatly reduces the size of each JOSM plugin.

In our case, OSMRec should depend on the following plugins:
- geotools
- jts
- log4j
- apache-commons

You can have a look to opendata or conflation plugins for examples. Tell me if some jars are missing in the geotools plugin and I'll add them (the plugin does only provide a small part of the library).

Thanks,
Vincent

**Comment by nkaragiannakis** [comment]
Hi!

i tried to do this when i was developing the plugin at first, but i had some problems with the versions of these libraries. Also, i noticed that the user had to download all the plugins that OSMRec depends to (or maybe i was doing something wrong?). 

Because i use only a part of these libraries, i thought that it would be better to ship these libraries inside the plugin. The problem of course was that the plugin ended up several megabytes..

Anyway, i 'll let you know if i need any missing jars as soon as i set up the new build script!

**Comment by don-vip** [comment]
Thanks!

The build.xml should become:

``` xml
<?xml version="1.0" encoding="utf-8"?>
    <project name="OSMRecPlugin" default="dist" basedir=".">

    <!-- enter the *lowest* JOSM version this plugin is currently compatible with -->
    <property name="plugin.main.version" value="8863"/>
    <property name="plugin.version" value="2.0"/>

    <!-- Configure these properties (replace "..." accordingly).
         See http://josm.openstreetmap.de/wiki/DevelopersGuide/DevelopingPlugins
    -->
    <property name="plugin.author" value="Nikos Karagiannakis - Athena RC"/>
    <property name="plugin.class" value="org.openstreetmap.josm.plugins.osmrec.OSMRecPlugin"/>
    <property name="plugin.description" value="Recommends categories/tags on newly created OSM entities by analysing spatial entities into training features and using SVM classification"/>
    <property name="plugin.icon" value="images/dialogs/logo-osmrec.png"/>
    <property name="plugin.link" value="http://wiki.openstreetmap.org/wiki/JOSM/Plugins/OSMRec"/>
    <property name="plugin.requires" value="log4j;apache-commons;jts;geotools"/>

    <!-- ** include targets that all plugins have in common ** -->
    <import file="../build-common.xml"/>

    <fileset id="plugin.requires.jars" dir="${plugin.dist.dir}">
        <include name="log4j.jar"/>
        <include name="apache-commons.jar"/>
        <include name="jts.jar"/>
        <include name="geotools.jar"/>
    </fileset>

</project>
```

**Comment by nkaragiannakis** [comment]
Ok i changed it and i deleted the included libraries from the plugin! Thanks!

**Comment by don-vip** [comment]
Great! I have removed remaining ones and updated the jar:
https://trac.openstreetmap.org/changeset/31702/subversion
https://trac.openstreetmap.org/changeset/31703/subversion

**Comment by don-vip** [comment]
I think we could also remove xml-apis-1.4.01.jar and xercesImpl-2.11.0.jar

Can you please try to see if the plugin works without them?

**Comment by nkaragiannakis** [comment]
I am not using these, they probably are left there from the CLI version.. I removed them and it works, so i updated the svn repo! 

**edit**: xercesImpl-2.11.0.jar was needed after all at the training process, so i added it again!
